# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project naveen.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'path/to/pom.xml'  # Path to your Maven project's pom.xml file
    goals: 'clean install'  # Build goals to execute

- task: Maven@3
  displayName: 'Jib Image Build'
  inputs:
    mavenPomFile: 'path/to/pom.xml'  # Path to your Maven project's pom.xml file
    goals: 'com.google.cloud.tools:jib-maven-plugin:3.1.4:build'  # Jib plugin goal to execute
