apiVersion: v1
kind: Service
metadata:
  name: __IMAGE__-service
  namespace: default
spec:
  selector:
    app: __IMAGE__
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
